version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examPapperManagement
      MYSQL_USER: uditha
      MYSQL_PASSWORD: SPAxim1@
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 5s
      timeout: 10s
      retries: 10
    security_opt:
      - seccomp:unconfined

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examPapperManagement?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=uditha
      - SPRING_DATASOURCE_PASSWORD=SPAxim1@
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./Frontend_1
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080  # Vite uses VITE_ prefix

volumes:
  db-data:
    driver: local

networks:
  webnet:
    driver: bridge