services:
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examPaperManagement
      MYSQL_USER: uditha
      MYSQL_PASSWORD: SPAxim1@
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 5s
      timeout: 10s
      retries: 10
    security_opt:
      - "seccomp:unconfined"

  backend:
    image: udithaimesh/ems:backend-latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examPaperManagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/ec2-user/Profile_Images:/app/uploads/profile_images
      - /home/ec2-user/Archived_Papers:/app/uploads/archived-papers
      - /home/ec2-user/Encrypted_Papers:/app/uploads/encrypted-papers
    networks:
      - webnet

  frontend:
    image: udithaimesh/ems:frontend-latest
    build:
      context: ./Frontend_1
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.53.133.27/api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://13.53.133.27/api/v1
    networks:
      - webnet


volumes:
  db-data:
    driver: local

networks:
  webnet:
    driver: bridge
