name: "Code Build Testing"

on:
  push:
    branches:
      - "development"
      - "main"
    paths:
      - Backend/**
      - Frontend_1/**
      - .github/workflows/buildCode.yml

  pull_request:
    branches:
      - "development"
      - "main"
    paths:
      - Backend/**
      - Frontend_1/**
      - .github/workflows/buildCode.yml

  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  actions: read
jobs:
  backend:
    name: Analyze and build backend Code
    runs-on: ubuntu-latest



    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Java for Java/Kotlin projects
      - name: Set up Java 21 (Adoptium)
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Build Java Code
        run: |
          echo "Building Java project with Maven in the Backend folder..."
          cd Backend
          ./mvnw clean compile -DskipTests

  frontend:
    name: build react frontend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20.18.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      - name: Build frontend
        run: |
          echo "Building JavaScript project in Frontend_1 folder..."
          cd Frontend_1
          npm install
          npm run build # Ensure this step produces JavaScript files in `dist`
  Docker:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push using Docker Compose
        run: |
            docker compose build
            docker compose push
        with:
          image: udithaimesh/ems
          context: .
          push: true
          tags: user/app:latest
 
